version: '3'
services:
  mongo:
    image: mongo:5.0.12
    restart: always
    container_name: OneAPI
    volumes:
      - ./mongo/data:/data/db
      - ./conf:/work/conf
    ports:
      - '27017:27017'
